# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d52fe1ddf3cfadfd18c4c91af6b1a5c11d64d277f83f6727d68b29d59f6635badf349ce489c0271e506f058aaa36789b3a50a9a2a3790b1559fd35461c66b74

test:
  secret_key_base: 2d52fe1ddf3cfadfd18c4c91af6b1a5c11d64d277f83f6727d68b29d59f6635badf349ce489c0271e506f058aaa36789b3a50a9a2a3790b1559fd35461c66b74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 2d52fe1ddf3cfadfd18c4c91af6b1a5c11d64d277f83f6727d68b29d59f6635badf349ce489c0271e506f058aaa36789b3a50a9a2a3790b1559fd35461c66b74
